//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewTask.BLL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceSetup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceSetup()
        {
            this.Regions = new HashSet<Region>();
        }
    
        public int InvoiceSetupID { get; set; }
        public string InvoiceNoCreationMethod { get; set; }
        public Nullable<bool> DiscountVisibility { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Region> Regions { get; set; }
    }
}
